### ISSUE TITLE
CBIBS data not loading

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/oceansmap#20]
CBIBS stations show "retrieval error" for all parameters.  Time-series plot shows data stopped updating at 5/25/16 0900 UTC.  Other products relying on SOS show CBIBS data so I don't think it's the CBIBS SOS feed.  Possible to resolve this today??

**Comment by kknee** [comment]
@kbailey-noaa NCBO said they would turn back on this afternoon.  Will confirm before closing this.

**Comment by kknee** [comment]
all set.
