### ISSUE TITLE
ENC basemap not fully loading

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/oceansmap#21]
The basemap has gray areas that don't load.  If I zoom in/out they load.
![enc](https://cloud.githubusercontent.com/assets/11823385/15611754/dde007bc-23f9-11e6-95bd-f1d617c089dd.PNG)

**Comment by lukecampbell** [comment]
That's part of the NOAA ArcGIS service, they are deliberately graying out those areas. This is outside the control of OceansMap:


![Here's what the service returns to us](http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/MapServer/export/export?bbox=-19920101.067343213%2C-812066.9885017116%2C-4578883.742395198%2C8883817.175416322&size=1568%2C991&dpi=96&format=png8&transparent=true&bboxSR=3857&imageSR=3857&f=image)

**Comment by lukecampbell** [comment]
That's literally what the service is returning to us at 

http://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime%20Chart%20Server/MapServer/export/export?bbox=-19920101.067343213%2C-812066.9885017116%2C-4578883.742395198%2C8883817.175416322&size=1568%2C991&dpi=96&format=png8&transparent=true&bboxSR=3857&imageSR=3857&f=image
