### ISSUE TITLE
WW3 wave pop data not updating

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/oceansmap#22]
Per image below - chose WW3 (wave height) and conus 5k NAM winds.  Discovered that no matter what timestamp I choose the pop up info (date/time and value) for WW3 height doesn't change.  Time-series show there is in fact data, and in the image below the current time (the vertical line) indicates there are data for that particular timestamp (5/27/160 0800).  Winds update, but waves don't.  I refreshed the map to start from scratch and issue didn't resolve itself.  Value seems to be 'stuck' on 5/26 20:00.

![ww3 issue](https://cloud.githubusercontent.com/assets/11823385/15617678/111d8c76-2418-11e6-9858-c4e0b4e0eb81.PNG)

**Comment by kknee** [comment]
this is fixed
