### ISSUE TITLE
Remove OFS from the winds list

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/oceansmap#31]
Remove all OFS layers from the winds list in the table of contents.  These are just NDFD or NAM winds, and are redundant.

**Comment by kknee** [comment]
@kbailey-noaa we will remove them from the list, but EDS will continue to collect them because the USCG uses them for SAROPS.  Do we need to have a follow up conversation about that?

**Comment by kknee** [comment]
this is all set on production.

**Comment by kbailey-noaa** [comment]
Nope, no need.
