### ISSUE TITLE
Caribbean NDBC buoys missing

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/oceansmap#38]
Buoy 42058 (SSE of Jamaica) is missing along with a couple others in the Caribbean.  Is there a boundary cut-off?

Not sure what the data source is.. I perused their THREDDS listing and the buoy isn't there.  But it is in their SOS: http://sdf.ndbc.noaa.gov/sos/server.php?request=GetCapabilities&service=SOS

**Comment by kknee** [comment]
yes, it's not in the region we collect, but we can add it.

**Comment by kknee** [comment]
@kbailey-noaa harvest piece complete, should be in the UI tomorrow.

**Comment by kknee** [comment]
this has been all set since last week: 

![image](https://cloud.githubusercontent.com/assets/196868/19387782/75d94ed0-91ea-11e6-94c4-195a7e0e22af.png)
